- example.js
- index.js
The extreme mode was buffering up the log, disabled for example
> Fixup example and options

- README.md
- example.js
- index.js
- test.js
@geek I think you would like this.
Do you think I should support a default for the `'allTags'` options, so all tags gets logged somehow?
> Server log support

- README.md
- example.js
- index.js
- package.json
cc @jamesdixon @davidmarkclements please review!
Fixes #4.
> Added the ability to prettyPrint the logs

- README.md
- Fix typo on onPostStop lifecycle method
> Fix typo on onPostStop lifecycle method

- .travis.yml
- README.md
- index.js
- test.js
Fixes #22.
This will be semver-major.
> Removed server.app.logger

- README.md
Removed references to pino in server.app from README
> server.app no more - update README

- example.js
- index.js
- package.json
> Restored prettyPrint support

- example.js
- index.js
- package.json
This backport a change from v3 (hapi@17) to v2 (hapi@16).
> [v2.x] Use prettyPrint from pino itself

- README.md
Sorry, I messed up the `pino-noir` example in https://github.com/pinojs/hapi-pino/pull/42.
Here is a fix for that.
> fix pino-noir example

- index.js
- package.json
- test.js
> clone the options object to prevent errors due to internal mutations, fixes #44

- index.js
- test.js
> Fix Hoek.merge regression

- index.js
- test.js
> ignore response logs for paths in ignorePaths

- .gitignore
- .travis.yml
- README.md
- index.js
- package.json
- test.js
Addresses #69 in the same way as #70, except for a different test implementation.
> Add support for hapi v18

- index.js
- test.js
addresses https://github.com/pinojs/hapi-pino/issues/74
> fix: log error instead of warn on 500s

- .gitignore
- index.js
- package.json
- test.js
I have updated all the depedencies and fixed few standard js issues
> updated depedencies and fixed few standard js issues

- README.md
See https://hapi.dev/api/?v=19.1.1#server.options.debug
Addresses #108
> Disable debug console logging in example config

- index.js
- test.js
> [master] prefer req.path instead of req.url.pathname

- README.md
- index.js
- test.js
Added a few feature - which enables us to filter the logs bases event tags.
> feat: Filter out logs based on event tags

- index.js
- test.js
See https://github.com/pinojs/pino/blob/master/docs/api.md#messagekey-string
> Respect `messageKey` option when `mergeHapiLogData` is set

- package.json
Hey, 
any chance to get the changes from https://github.com/pinojs/hapi-pino/pull/138 out as a release? I've installed from GitHub by commit hash until now, but it's now making some problems, so I'd love to have an npm release :)
Thanks!
> Bumped v8.4.0

- index.d.ts
- index.test-d.ts
Adding type definitions for options added in #163
> Add missing type definitions for custom message properties

- README.md
> Add note about deprecated option

- index.d.ts
- index.test-d.ts
> Update wrapSerializers type to be optional
