README.md
index.js
test.js

This PR adds default mappings for tags to log levels. This reduces the amount of configuration necessary to use the plugin in a standard logging style.

Add default tag mappings

---

README.md
index.js
test.js

If you have previously created an instance of Pino, prior to initializing your Hapi instance, it should be possible to use that instance of Pino within the plugin. This PR adds such support.

Add support for using prior Pino instance

---

index.js
test.js

Hey,
I was testing my apply with hapi 16.1.1,  specifically, the way it handles invalid accept-encoding error since accept-encoding.
Looks like this is not working, because, when hapi is checking the error, it does `request.log`.
But at this point, the logger is not yet attached to the request, that is why it fails.
```
TypeError: Cannot read property 'error' of undefined
at logEvent (PROJECT/node_modules/hapi-pino/index.js:106:16)
at PROJECT/node_modules/hapi-pino/index.js:64:5
at invoke (PROJECT/node_modules/hapi/node_modules/podium/lib/index.js:239:30)
at each (PROJECT/node_modules/hapi/node_modules/podium/lib/index.js:243:13)
at Object.exports.parallel (PROJECT/node_modules/hapi/node_modules/items/lib/index.js:70:13)
at Object.internals.emit …
```

Fix bad encoding

---

README.md
benchmarks/hapi-pino-merge-hapi-log.js
benchmarks/hapi-pino-no-merge-hapi-log.js
index.js
test.js

With this PR, users can specify a `mergeHapiLogData` option when registering the plugin. 
```js
{
register: 'hapi-pino',
options: {
mergeHapiLogData: true // Default is false.
}
}
```
When enabled, the data attribute from hapi log events (e.g. `server.log([tags], data)`, `request.log([tags], data)`) will be merged straight into pino's log object. 
```js
server.log(['info'], { hello: 'world' });
{ level: 30, hello: 'world', ...}
```
Additionally, string only logs will be merged under the msg attribute.
```js
server.log(['info'], 'hello world');
{ level: 30, msg: 'hello world', ...}
```
When disabled (default value), the data attribute will be included under a data key. This is the current behaviour (before this PR)
```js
server.log(['info'], { hello: 'world' });
{ level: 30, data: { hello: …
```

Adds support for mergeHapiLogData plugin-level option. Fixes #15

---

README.md
index.js
test.js

This PR adds a `logEvents` plugin-level option. This options allows user to specify the server events that the library should log.
```js
{
register: 'hapi-pino',
options: {
logEvents: ['onPostStart', 'onPostStop', 'response', 'request-error'] // Default value, logs all events.
}
}
```
Users can disable all logged events by specifying `logEvents: false|null`.

Allows users to choose which events to log.

---

README.md
index.js
test.js

Related to #13 
- Add possibility to define custom serializers
- Add option `logPayload` to log request payload

Add possibility to define custom serializers for req, res and err

---

README.md
index.js
test.js

#33 
- fix description of `logEvents` options
- enable obligatory logging of `request.log()`; just the logging of errored requests is optional.
--> backward compatibility with `v1.x.x`
#31 
- fix description of `log` event
- fix description of `request` event

Fix Hapi Event Handling and Documentation

---

index.js
package.json
test.js

This is my first pass at this.  
My goals were:
- Little to no impact if not used
- Preprocess as much as possible
closes #26

FEAT: Support `ignorePaths` option to exclude certain paths from logging.

---

README.md
index.js
test.js

This allows the tags in hapi `route.options.tags` to be part of the logged data. This is useful to e.g. classify the requests in a dashboard.
two tests are added testing for the correct behaviour in both cases `logRouteTags: true` and the absence of this option property.

feat(route-tags): logs route tags if options.logRouteTags is true

---

index.js
test.js

Add the handling of errors logged with `server.log()` — those get ignored up to now.
Adjust the behavior to `request.log()`

log error with server.log

---

README.md
index.js
test.js

This wraps custom serializers in the same way as implemented in https://github.com/pinojs/pino-http/pull/43.
This PR replaces https://github.com/pinojs/hapi-pino/pull/34.
Most of the code is copied from the implementation in https://github.com/pinojs/pino-http/pull/43 with small adjustments for hapi specific things.
Tests are updated to test for the existence of `req.raw` and `res.raw` in custom serializers.

wrap custom serializers

---

index.js

As titled. Sometimes we don't get our logger, not sure when but we need to protect against that.

Protect against 'request' lifecycle not firing

---

index.js
package.json
test.js

This adds the `ignorePaths` option by cherry-picking the commits from PR #30 and adapting for Hapi V16

Backport ignorePaths support to v2.x.x

---

README.md
index.js
package.json
test.js

Backport 42 to v2.x.x

---

README.md

Documented that providing a `level` in the options map passes that to https://github.com/pinojs/pino/blob/master/docs/API.md#level

Added documentation around the `level` option

---

package.json

This PR bumps `hoek` and `lab` versions to avoid warnings like these:
```
warning lab > hoek@5.0.4: This version is no longer maintained. Please upgrade to the latest version.
warning lab > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
```

Bump hoek and lab to avoid warnings about unmaintained packages.

---

index.js
test.js

According to the hapi 18 release notes, `request.url.path` has gone away in favor of `request.path` or `request.url.pathname`. The same release notes also state that `request.url.pathname` has not changed.
Refs: https://github.com/hapijs/hapi/issues/3871

update ignorePaths logic

---

package.json

This PR bumps pino to v5.12.3 to include browser fix from https://github.com/pinojs/pino/pull/612
It enables `hapi-pino` to be used within Hapi embedded in WebExtension context:  https://github.com/ipfs-shipyard/ipfs-companion/issues/664 https://github.com/ipfs-shipyard/ipfs-companion/issues/716

Improve browser support

---

benchmarks/hapi-pino-extreme.js
benchmarks/hapi-pino-merge-hapi-log.js
benchmarks/hapi-pino-no-merge-hapi-log.js
benchmarks/hapi-pino.js
benchmarks/hapi-pure.js
example.js
index.js
package.json
test.js

Change dependencies to the new scoped hapi packages to get rid of the deprecation warnings and to make sure new updates to these packages are used in hapi-pino as well. 
Updated example, index and tests to use the new packages accordingly, functionality wise nothing changes.

Fix hapi dependencies to use new scoped @hapi packages

---

index.js

rather than exporting all symbols in pino browser which adds payload overhead and causes back compat issues  (https://github.com/pinojs/pino/pull/647 IE11 doesn't support Symbols - the alternative is more payload overhead for a polyfill) we can use `Symbol.for` instead in hapi-pino to support the case from https://github.com/pinojs/pino/pull/612

niche browser support case (cf https://github.com/pinojs/pino/pull/612)

---

index.js
test.js

A few days ago I ran into a bug where logging via `request.log` would cause unhandled promise rejection warnings on routes with disabled logging. I traced it down to [this line](https://github.com/pinojs/hapi-pino/blob/master/index.js#L172). Basically on an ignored route, `current` is equal to the `nullLogger` which doesn't have a `levels` property. 
- Add a `request.log([level])` statement within a route handler such that `level` is a valid log level configured within hapi-pino such as 'info', 'warn', 'error', etc.
- Disable that route by adding it to `ignorePaths`
- Make a request to that route
I've added a unit test which reproduces this bug.

Fix UnhandledPromiseRejection warning when logging on an ignored path

---

README.md
index.js
test.js

Related suggestion issue: https://github.com/pinojs/hapi-pino/issues/86
This PR adds an optional `options.getChildBindings(request) => Pino.Bindings` function to the hapi-pino options object.
This allows you to customize the bindings being passed into `logger.child()`, which was previously hardcoded to always be `{ req: request }`
If omitted, it keeps the old behavior of `{ req: request }`
```javascript
const plugin = {
plugin: Pino,
options: {
stream: stream,
level: 'info',
getChildBindings: (req) => ({ custom: true })
}
}
await server.register(plugin)
```

feat: add options.getChildBindings()

---

README.md
index.js
test.js

After my recent `getChildBindings` addition, if you omit `req` from your child bindings, then the "request complete" log event does not include the `req`
Adding a `options.logRequestStart` boolean that automatically logs each new request as soon as it comes in.
This pairs nicely with `getChildBindings` when you omit the `req`, as it logs the request and the response separately without duplicating information.  The two events (and any events in the middle at the app-level) can be linked together with a requestId e.g. 
```js
logRequestStart: true,
getChildBindings: (request) => ({ requestId: request.headers['x-request-id'] }),
```
Background/approach context:
I originally tried making the new "request start" event a custom function like `options.onRequestStart: (request) => void`, where you …

fix missing req in "request complete" event when using getChildBindings and options.logRequestStart feature

---

README.md

Updates the docs to be a little more structured + have typedefs included for those so inclined
Also brings it closer in parity to pino's docs ( https://github.com/pinojs/pino/blob/master/docs/api.md#pinooptions-destination--logger )
Before:
After:

docs: improve API docs in README; add types, improve formatting

---

index.js
test.js

fix: use scoped logger if request.logger is not available

---

README.md
index.js
test.js

Stacked on top of https://github.com/pinojs/hapi-pino/pull/89 for formatting improvements to the README
This PR:
- adds the ability to specify the existing `options.logRequestStart` using a function syntax: `(Request) => boolean`, which selectively enables/disables the logging on requestStart for the given request
- adds the same functionality for the "request complete" event, letting you pass in either a boolean or a function of the same style.
- keeps the current behavior / defaults, namely:
- `request start` events are _not_ logged
- `request completed` events _are_ logged

Feat: add options.logRequestComplete, allow function syntax for options.logRequestStart

---

README.md
index.js
test.js

Usually we wants to group multiple routes in tags, however ignoring these routes one by one seems to be a tedious process. It would make more sense to support such a case by just ignoring through the tags instead, hence this PR.

feat: ignored by tags

---

README.md
index.js
test.js

BREAKING CHANGE: Instead of calling `server.logger()` to get the logger instance of the server it can now be destructured directly `server.logger`
Closes #98

refactor: server.logger() function removed in favor of server.logger

---

index.js
test.js

[master] fix: get securely pathname from request url

---

test.js

This is a proposal to fix the test that's currently blocking #123, #124 and #125. 
Tbh I'm not 100% sure if it's the right fix - for some reason, simulating a connection close seems to make hapi fail internally for POST requests, it has nothing to do with this test (the functionality seems to work fine AFAICT). For some reason, it works with GET requests though. 
I'm adding a separate route with an artificial delay instead of just hitting `GET /something`, as otherwise the assertion on the response time being greater than 0 is flaky, as it sometimes _is_ 0, depending on how quick the test runs.

Fix test case for simulating a closed connection

---

.github/workflows/test.yml
README.md
index.js
package.json

Bump pino version from 6.0.0 to 7.0.0

---

benchmarks/hapi-pino-with-pino-pretty.js
package.json

This pr will upgrade the @hapi/hapi to V20.2.1
and the pino-pretty@4.0.0
With one example on how to use pretty logs!

Update to @hapi/hapi@20.2.1 and pino-pretty@7.2.0

---

package.json

`pino-pretty` seems to be only useful as part of the benchmarking code, so moving to dev dependencies instead.

Move pino-pretty as a dev dependency

---

index.d.ts
index.test-d.ts
package.json

@types/hapi-pino is not compatible with pino's type declarations: [https://github.com/pinojs/pino/blob/38ff645e7fd1a62ccffaa710070a03ba71495f1e/pino.d.ts](url)
The goal of this PR is to make @types/hapi-pino unnecessary.

Add type declarations

---

index.js
test.js

Hi @ovhemert! Thanks for this information! at issue #145  This will be so helpful for us! So i maked this pr with these changes?
Replace the `event.error` condition [here](https://github.com/pinojs/hapi-pino/blob/master/index.js#L120-L124)
with  
```
if (!isCustomTagsLoggingIgnored(event, ignoredEventTags.log)) { // first check on ignoring tags
if (event.error) {
logger.error({ err: event.error })
} else {
logEvent(logger, event)
}
}
```
so after this change should be able to ignore this events tags as you are showing here... right?
```
await server.register({
plugin: require('hapi-pino'),
options: {
prettyPrint: true,
ignoredEventTags: { log: ['client'], request: '*' }
}
})
```

Fix read ECONRESET error #145

---

index.js
test.js

The number/data from the log was being erased by the `Object.assign`.

fix: allow logging numbers when mergeHapiLogData is true

---

index.js
package.json
test.js

Code changes were done with `standard --fix`.

fix: update dependencies

---

index.js
test.js

feat: change response message to response summary

---

README.md
index.js
test.js

There is no way to know in the response log event handling if the request was already added through the child bindings in `onRequest`.
And there was no way as a user to fix this behaviour properly.
So now `req` will be added once but you need to make sure that you pass it in `childBindings` for the response.
Request start event will have it regardless but also only once.
This is a breaking change as some people will have removed the `req` from the `childBindings` to get around this issue.
Fixes https://github.com/pinojs/hapi-pino/issues/91

fix!: prevent `req` being added twice to the response and request start log

---

README.md
index.js
test.js

hapi-pino [9.2.0](https://github.com/pinojs/hapi-pino/releases/tag/v9.2.0) and [9.3.0](https://github.com/pinojs/hapi-pino/releases/tag/v9.3.0) added a few changes to the default output of "[request completed](https://github.com/pinojs/hapi-pino/pull/156)" and "[request error](https://github.com/pinojs/hapi-pino/pull/159)", that while useful for certain transports it can be redundant for others (the same information is already included). This pull request adds a way to customize these messages without changing the defaults:
- `customRequestStartMessage` - to customize messages when enabled by `logRequestStart`
- `customRequestCompleteMessage` - to customize messages when enabled by `logRequestComplete`
- `customRequestErrorMessage` - to customize request error messages
These properties …

Add support for custom messages on request completion/receive/failure

---

README.md
index.d.ts
index.js
index.test-d.ts
test.js

hapi-pino binds the request only once during the `onRequest` hook:
https://github.com/pinojs/hapi-pino/blob/27806507920fda5db27c2daca0a99259423ba647/index.js#L111-L118
However, hapi only makes `request.params` available later in the [request lifecycle](https://hapi.dev/api/?v=20.2.2#request-lifecycle), and it is accessible only after `onPreAuth` at the earliest. This pull request adds optional support to log `pathParams` when `logPathParams` is `true`, in pretty much the same way that `logQueryParams` works

Add optional support to log path params

---

index.js
test.js

When a request has been [abandoned](https://hapi.dev/api/?v=20.2.2#h.abandon) by hapi.js and ends ultimately aborted, then the `request.raw.res.statusCode` is only valid when headers have been flushed.

Log correct status code on aborted requests

---

README.md
index.d.ts
index.js
index.test-d.ts
test.js

Presently is not really possible to completely replace hapi-pino's default serializers with a custom implementation as `req` and `res` serializers are always wrapped with the standard serializers. This pull request adds support to replace them unwrapped by providing the `wrapSerializers` option set to `false`

Add support to replace default serialalizers unwrapped

---

package.json
test.js

Updates pino to version 8.5.0 and pino-pretty to 7.6.1
There is a change in pinos standard response serializer, where statusCode is set to null if headers are not sent, therefore the change in test

Update to pino@8.5.0 and pino-pretty@7.6.1

---

README.md
index.test-d.ts

No longer a valid option since pino 8.x.

Remove prettyPrint from documentation and typedefs

---

.github/workflows/test.yml
README.md
index.test-d.ts
package.json

Addresses issue: https://github.com/pinojs/hapi-pino/issues/179

Update dependencies to support Hapi v21

---

README.md
index.d.ts
index.js
package.json
test.js

Fixes #111 
This PR adds a new option `log4xxResponseErrors` that, when true, will add the error details to the response log under the key `err` (chosen to match 500 error logging).
For example:
```
{"level":30,"time":1683229159104,"pid":92186,"hostname":"jeff-MacBook-Pro","req":{"id":"1683229159103:jeff-MacBook-Pro:92186:lh9j6jej:10000","method":"get","url":"/","query":{},"headers":{"user-agent":"shot","host":"jeff-MacBook-Pro:0"},"remoteAddress":"127.0.0.1","remotePort":""},"err":{"type":"Object","message":"invalid request","stack":"","statusCode":400,"error":"Bad Request"},"res":{"statusCode":400,"headers":{"content-type":"application/json; charset=utf-8","cache-control":"no-cache","content-length":68}},"responseTime":1,"msg":"[response] get / 400 (1ms)"}
```
This pulls the response …

add option to log 4xx error details in request logs

---

README.md
index.d.ts
index.js
test.js

Fixes https://github.com/pinojs/hapi-pino/issues/183 .
I couldn't find a way to do this with any existing `options` so here's a PR that allows specifying the log level for request start, request complete and request error events.
It can be useful to log the request start/complete messages on a lower level, such as `debug`. For example, if there is too much traffic to log every single request, and you wish to log on `debug` level by default, and later in the pipeline decide to drop or keep those log entries.

Allow specifying level for request start/complete logging
